### ISSUE TITLE
how to run sample code?

### ISSUE THREAD

**Issue by taskx6004** [PacktPublishing/Effective-Robotics-Programming-with-ROS#1]
Hi,
I am new to ROS, (that's why i need this book) and i could not figure out how to run the code. After I downloaded the zip file, i extracted it, it looks like not built, but in Chapter3: "Debugging ROS node" the command: 
`$ rosrun chapter3_tutorials example1`
obviously not working.

And the:
`$ cd devel/lib/chapter3_tutorials`
which infers to i should have a built samples downloaded.

Then i try to build the source. I copied a clean folder of chapter3_tutorials, and used catkin_init_workspace to initialize it in src folder, but when use catkin_make in it's parent folder, i get an error:
The specified base path "<mypath>/chapter3_Code" contains a pakage but "catkin_make" must be invoked in the root of workspace

How should i use the sample code?

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if this error still exists. Thanks!
